### ISSUE TITLE
?

### ISSUE THREAD

**Issue by kentikzlo** [Minejong/ext-chunkutils2#1]
где репо minecraftserver? что за удаленный git аккаунт?

**Comment by Minejong** [comment]
![PicsArt_12-17-06 11 07](https://user-images.githubusercontent.com/55767127/71008509-c7d82c00-20f9-11ea-8a82-317f040d1b6b.jpg)
Написал в поддержку, жду...

**Comment by kentikzlo** [comment]
ладно, buildbattle доделаешь?

**Comment by Minejong** [comment]
Там скорее не доделать его надо, а переделать...
Автор buildbattle похоже не предусмотрел, что в его код будет лезть кто-то другой и не документировал его - так и не пон, что за что отвечает.
И что самое печальное - автор сделал код явно не лучшего качества, не поставил даже таймингов, из-за чего опять же не понятно, где надо искать проблемы. Предполагаю, что большая нагрузка из-за большого объёма плохого кода, особенно в zones.(в других папках, вероятно, он не лучше - не особо обратил на это внимание)

Пока что не придумал, что с этим можно сделать...


Ну и в данный момент я работаю над этим репо, так как с ним легко и интересно работать.
"Что это за репо?" - это расширение на C++, которое должно будет прям огромный скачок в скорости сделать с пакетами и чанками. C++, как ни странно, быстрее PHP в сотни/тысячи раз и думаю вот доделать это репо. :/

**Comment by kentikzlo** [comment]
понял, а это расширение будет только с 1.2.13+ работать, как и "стандартный" chunk utils?

и с тобой как-то адекватно можно связаться, а не через issues?

**Comment by Minejong** [comment]
> а это расширение будет только с 1.2.13+ работать

Там уже конвертер есть как-бы.
Вроде как конвертирует чанк с нового формата на старый за примерно 0.00000... кароче очень быстро.(затрата времени на конвертацию рил очень маленькое, кол-во нулей не запомнил :Р)
> и с тобой как-то адекватно можно связаться

Через некоторое время в VK "вернусь", как только хотя-бы проблемы с `BinaryStream.h` решу в этом репо.

**Comment by kentikzlo** [comment]
сейчас есть какой-то гайд чтобы этот ext установить? я мб к себе на прод поставлю, как раз будет "живой" пример как эта штука работает

**Comment by Minejong** [comment]
Там не всё просто: мне пришлось примерно дня 2 потратить когда-то на "нормальную поддержку" софтом PalettedBlockArray и там были некоторые печальны изменения: пришлось убрать Level->setBlockIdAt(), setBlockDataAt(), getBlockIdAt(), getBlockDataAt() и осталось только getFullBlock/setFullBlock.
Эти изменения ломают плагины :(

Но всё-же оно кушает в разы меньше памяти и работает быстрее.(если сравнивать с чанками, которые в данный момент на stable ветке пммп)

**Comment by kentikzlo** [comment]
не знаешь когда примерно эту утилиту доделаешь чтобы нормально работала?

**Comment by Minejong** [comment]
Она не работает?
![PicsArt_12-19-09 44 52](https://user-images.githubusercontent.com/55767127/71200381-f9432a00-22a8-11ea-8819-82271409a3a1.jpg)
![Screenshot_20191219_212047_com mojang minecraftpe1](https://user-images.githubusercontent.com/55767127/71200402-019b6500-22a9-11ea-87eb-db490c4bf054.jpg)

**Comment by kentikzlo** [comment]
ну, ты сказал что пришлось убрать методы, и из-за этого плагины ломаются
